# Generated by Django 2.2.3 on 2020-03-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='context',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='keyword',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
