# Generated by Django 3.0.5 on 2020-04-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_setsattempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='set_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
