# Generated by Django 3.0.5 on 2020-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200412_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
