# Generated by Django 3.0.5 on 2020-04-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200412_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='set_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
