# Generated by Django 3.0.5 on 2020-04-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_choice_set_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_type',
            field=models.CharField(default='P', max_length=5),
            preserve_default=False,
        ),
    ]
