# Generated by Django 3.0.6 on 2020-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200516_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_valid',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
